import type { Metadata } from "next";
import PublicPageFrame from "../../src/components/PublicPageFrame";
import { LEGAL_EFFECTIVE_DATE, SUPPORT_EMAIL, SUPPORT_LOCATION } from "../../src/siteDetails";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <PublicPageFrame>
      <article className="sc-legal-page">
        <header className="sc-legal-hero">
          <p>Trust centre · Privacy</p>
          <h1>Privacy<br />Policy</h1>
          <div><span>Effective {LEGAL_EFFECTIVE_DATE}</span><span>Clear purpose · Limited collection</span></div>
        </header>
        <div className="sc-legal-layout">
          <aside aria-label="Privacy contents"><strong>On this page</strong><a href="#overview">Overview</a><a href="#collect">Information collected</a><a href="#use">How it is used</a><a href="#ai-privacy">AI and images</a><a href="#sharing">Service providers</a><a href="#retention">Retention</a><a href="#security">Security</a><a href="#rights">Your choices</a><a href="#minors">Minors</a><a href="#privacy-contact">Contact</a></aside>
          <div className="sc-legal-copy">
            <section className="sc-privacy-cards" aria-label="Privacy highlights"><div><strong>Essential cookie only</strong><p>The LaneLab session cookie keeps you signed in and is not an advertising tracker.</p></div><div><strong>Images are request-based</strong><p>AI images are processed for the current request and are not saved to a LaneLab image library in this release.</p></div><div><strong>No data sale</strong><p>LaneLab does not sell personal information or use it for behavioural advertising.</p></div></section>
            <section id="overview"><span>01</span><h2>Overview and accountability</h2><p>This Policy explains how LaneLab collects, uses, discloses, retains, and safeguards personal information when you use the public website, create an account, access the studio, or use AI-assisted features. LaneLab is responsible for the personal information under its control.</p><p>Our privacy contact is available at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. The contact details in this launch version are placeholders and must be replaced before commercial operations.</p></section>
            <section id="collect"><span>02</span><h2>Information we collect</h2><ul><li><strong>Account information:</strong> name, email address, password hash, optional phone number, swim club, role, city or region, and primary course.</li><li><strong>Authentication information:</strong> hashed session and password-reset tokens, expiry times, and an essential login cookie.</li><li><strong>Coaching content:</strong> prompts, workouts, race context, athlete notes, and other information you choose to enter.</li><li><strong>AI image input:</strong> a JPEG, PNG, or WebP image you choose to attach for a specific AI request.</li><li><strong>Technical information:</strong> limited request, error, security, and device information produced by the hosting environment.</li><li><strong>Device-local information:</strong> current workout drafts, saved projects, panel preferences, custom blocks, and calendar plans may be stored in your browser.</li></ul></section>
            <section id="use"><span>03</span><h2>Why we use information</h2><p>We use information to create and secure accounts, maintain sessions, provide requested planning and analysis tools, process password recovery, personalize basic club context, generate exports, answer AI requests, prevent misuse, diagnose errors, and meet legal obligations.</p><p>We do not use account or coaching content for behavioural advertising. If we introduce a materially new purpose, we will update this Policy and obtain consent where required.</p></section>
            <section id="ai-privacy"><span>04</span><h2>AI prompts and image processing</h2><p>When live AI is configured and you submit a prompt or image, the request may be sent to Google’s Gemini service to generate a response. Include only information needed for the coaching question. Do not upload medical records, government identifiers, or identifiable images without permission.</p><p>Attached images are held in browser memory, sent with the request, and not written to LaneLab’s database or object storage in this release. The configured AI provider may process request data under its own service terms and privacy commitments. Offline-safe responses do not send the image to an AI provider.</p></section>
            <section id="sharing"><span>05</span><h2>Service providers and disclosure</h2><p>LaneLab may use hosting, database, security, email-delivery, and AI service providers that process information on our behalf. We limit disclosure to what is reasonably needed for the service. We may also disclose information when required by law, to protect safety or security, or as part of a legitimate business transaction with appropriate safeguards.</p><p>Information may be processed outside your province or country and may be subject to the laws of that location.</p></section>
            <section id="retention"><span>06</span><h2>Retention and deletion</h2><p>We keep account information while the account is active and for a reasonable period needed for security, dispute resolution, and legal compliance. Sessions expire automatically. Password-reset tokens expire quickly and cannot be reused. We retain other information only as long as needed for the stated purpose.</p><p>Browser-stored workouts and preferences remain on the device until you clear them or use an available deletion control. You may request account-data deletion through the privacy contact, subject to legal or security retention requirements.</p></section>
            <section id="security"><span>07</span><h2>Security</h2><p>LaneLab uses salted password hashing, hashed session and reset tokens, HttpOnly cookies, server-side authorization, input limits, and encrypted transport in production. No system is perfectly secure; use a unique password and report suspicious activity promptly.</p></section>
            <section id="rights"><span>08</span><h2>Your access and choices</h2><p>You may ask whether LaneLab holds personal information about you, request access, correct inaccurate information, withdraw consent where applicable, or request deletion. We may need to verify your identity and may retain information where law permits or requires it.</p><p>You can block cookies in your browser, but the essential session cookie is required to remain signed in. LaneLab does not currently use third-party advertising cookies.</p></section>
            <section id="minors"><span>09</span><h2>Minors and athlete information</h2><p>Clubs and coaches are responsible for obtaining appropriate authorization before entering information about an athlete or uploading an athlete image. Do not submit identifying information about a minor unless the parent, guardian, club, and applicable policies permit it. LaneLab should not be used by a child without appropriate adult supervision.</p></section>
            <section><span>10</span><h2>Changes to this Policy</h2><p>We may update this Policy to reflect product, provider, or legal changes. We will update the effective date and provide additional notice when appropriate.</p></section>
            <section id="privacy-contact"><span>11</span><h2>Privacy questions and complaints</h2><p>Contact the LaneLab privacy lead at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Include “Privacy request” in the subject line and never send your password. Placeholder mailing location: {SUPPORT_LOCATION}.</p></section>
          </div>
        </div>
      </article>
    </PublicPageFrame>
  );
}

