import {
  PoolLength,
  PoolUnit,
  StudioNode,
  createSetNode,
} from "./swimStudioEngine";

export interface FamousWorkout {
  id: string;
  title: string;
  subtitle: string;
  attribution: string;
  sourceName: string;
  sourceUrl: string;
  level: "Beginner" | "Intermediate" | "Advanced" | "Elite";
  focus: string;
  phase: string;
  durationMinutes: number;
  poolLength: PoolLength;
  poolUnit: PoolUnit;
  tags: string[];
  disclaimer: string;
  nodes: StudioNode[];
}

const section = (title: string, purpose: string, pointsOfPerformance: string, children: StudioNode[]): StudioNode => ({
  id: `famous-section-${Math.random().toString(36).slice(2)}`,
  kind: "section",
  title,
  purpose,
  pointsOfPerformance,
  children,
  locked: false,
});

const repeat = (label: string, rounds: number, children: StudioNode[]): StudioNode => ({
  id: `famous-repeat-${Math.random().toString(36).slice(2)}`,
  kind: "repeat",
  label,
  rounds,
  children,
  locked: false,
});

const note = (label: string, text: string): StudioNode => ({
  id: `famous-note-${Math.random().toString(36).slice(2)}`,
  kind: "note",
  label,
  text,
  locked: false,
});

const sourceDisclaimer = "Adapted into editable SetCraft blocks from a publicly described workout concept. Intervals and volumes must be adjusted by a qualified coach for the swimmers, pool and training phase.";

export const FAMOUS_WORKOUTS: FamousWorkout[] = [
  {
    id: "beginner-skills-foundation",
    title: "Skills and Drills Foundation",
    subtitle: "A beginner-friendly technique session built around streamlining, sculling, rotation and pacing basics.",
    attribution: "Inspired by Olivier Poirier-Leroy's beginner skills workout",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Beginner",
    focus: "Fundamental skills and confidence",
    phase: "General preparation",
    durationMinutes: 45,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Technique", "Beginner", "Drills"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Comfort and breathing rhythm", "Relaxed exhale; long body line", [
        createSetNode("warm-up", { label: "Easy freestyle", reps: 2, distance: 100, stroke: "Free", interval: "2:15", breathingPattern: "Every 3", notes: "Smooth and relaxed" }),
      ]),
      section("Skill circuit", "Build feel for the water and streamline control", "Hands hold pressure; tight streamline; balanced rotation", [
        repeat("Technique circuit", 3, [
          createSetNode("drill", { label: "Vertical hand scull", reps: 2, distance: 0, interval: "0:30", intervalMode: "rest", restSeconds: 10, equipment: [], notes: "20 seconds of controlled sculling" }),
          createSetNode("underwater", { label: "Streamline push for distance", reps: 3, distance: 10, interval: "0:35", equipment: [], notes: "Measure distance before surfacing" }),
          createSetNode("drill", { label: "Side-kick balance", reps: 4, distance: 25, stroke: "Free", interval: "0:50", equipment: ["Fins"], notes: "One arm extended" }),
          createSetNode("drill", { label: "Overkick freestyle", reps: 4, distance: 25, stroke: "Free", interval: "0:45", equipment: [], notes: "Normal arms, fast kick" }),
        ]),
      ]),
      section("Cool-down", "Reset technique", "Quiet kick; relaxed breathing", [createSetNode("recovery", { label: "Easy choice", reps: 2, distance: 100, interval: "2:15" })]),
    ],
  },
  {
    id: "conditioning-ladder",
    title: "Conditioning Ladder",
    subtitle: "A descending distance ladder that holds one base pace while the repetitions get shorter.",
    attribution: "Inspired by the Conditioning Ladder workout",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Intermediate",
    focus: "Aerobic pacing and mental consistency",
    phase: "Aerobic base",
    durationMinutes: 60,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Aerobic", "Ladder", "Pacing"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare every system", "Progressive effort; clean turns", [createSetNode("warm-up", { label: "Swim / IM drill / kick / swim", reps: 4, distance: 100, interval: "1:50", notes: "Rotate mode every 100" })]),
      section("Descending ladder", "Hold the same pace per 100 throughout", "Even pacing; no early surges; strong final 100", [
        createSetNode("aerobic", { label: "500 freestyle", reps: 1, distance: 500, interval: "7:30", notes: "Base 1:30 per 100" }),
        createSetNode("aerobic", { label: "400 freestyle", reps: 1, distance: 400, interval: "6:00" }),
        createSetNode("aerobic", { label: "300 freestyle", reps: 1, distance: 300, interval: "4:30" }),
        createSetNode("aerobic", { label: "200 freestyle", reps: 1, distance: 200, interval: "3:00" }),
        createSetNode("threshold", { label: "100 strong", reps: 1, distance: 100, interval: "1:30", intensity: 8, notes: "Best controlled finish" }),
      ]),
      section("Cool-down", "Lower heart rate", "Long strokes", [createSetNode("recovery", { label: "Easy choice", reps: 2, distance: 100, interval: "2:00" })]),
    ],
  },
  {
    id: "distance-per-stroke-deluxe",
    title: "Distance Per Stroke Deluxe",
    subtitle: "A stroke-count constraint workout that challenges swimmers to preserve speed with fewer strokes.",
    attribution: "Inspired by the Distance Per Stroke Deluxe set",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Intermediate",
    focus: "Efficiency at speed",
    phase: "General preparation",
    durationMinutes: 65,
    poolLength: 25,
    poolUnit: "m",
    tags: ["DPS", "Freestyle", "Efficiency"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare catch and body line", "Count strokes without forcing glide", [createSetNode("warm-up", { label: "Swim / kick / drill", reps: 3, distance: 200, interval: "3:30" })]),
      section("Baseline", "Establish normal stroke count at strong aerobic speed", "Accurate count; stable pace", [createSetNode("test-set", { label: "Baseline 50", reps: 2, distance: 50, interval: "1:30", intensity: 7, notes: "Record time and stroke count" })]),
      section("Main set", "Reduce strokes while preserving speed", "Hold water; accelerate through the back of the stroke", [
        repeat("Stroke-count cycle", 8, [
          createSetNode("threshold", { label: "Baseline stroke count", reps: 1, distance: 50, interval: "1:00", intensity: 8 }),
          createSetNode("threshold", { label: "Baseline minus one stroke", reps: 1, distance: 50, interval: "1:00", intensity: 8 }),
          createSetNode("threshold", { label: "Baseline minus two strokes", reps: 1, distance: 50, interval: "1:00", intensity: 8 }),
        ]),
      ]),
      section("Cool-down", "Restore length", "Easy tempo", [createSetNode("recovery", { label: "Easy swim", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "bob-bowman-kick",
    title: "Bob Bowman Kick Set - Adapted Practice",
    subtitle: "A repeatable moderate-50 / fast-100 kick pattern designed to challenge leg endurance and quality.",
    attribution: "Based on a publicly described Bob Bowman kick set",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Advanced",
    focus: "Kick endurance and finishing speed",
    phase: "Race preparation",
    durationMinutes: 60,
    poolLength: 25,
    poolUnit: "yd",
    tags: ["Kick", "Bowman", "Power"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare legs and ankles", "Loose ankles; narrow kick", [
        createSetNode("warm-up", { label: "Choice warm-up", reps: 1, distance: 600, interval: "12:00" }),
        createSetNode("kick", { label: "Kick descend", reps: 4, distance: 50, interval: "1:00", notes: "Descend 1-4" }),
      ]),
      section("Main kick set", "Sustain moderate work and attack the 100", "About 10 seconds rest on repeat kick; fast walls", [
        repeat("Bowman kick round", 6, [
          createSetNode("kick", { label: "Moderate kick", reps: 2, distance: 50, interval: "0:55", equipment: ["Kickboard"], intensity: 7 }),
          createSetNode("kick", { label: "Fast kick", reps: 1, distance: 100, interval: "1:35", equipment: ["Kickboard"], intensity: 9 }),
        ]),
      ]),
      section("Cool-down", "Flush the legs", "Relaxed body line", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 400, interval: "8:00" })]),
    ],
  },
  {
    id: "phelps-descending-rest",
    title: "Descending-Rest 100 Pace Challenge",
    subtitle: "Race-pace 50s with progressively less recovery, followed by substantial easy swimming.",
    attribution: "Associated with Richard Quick and frequently used by Michael Phelps",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Elite",
    focus: "Back-half speed and pace under fatigue",
    phase: "Race preparation",
    durationMinutes: 80,
    poolLength: 25,
    poolUnit: "yd",
    tags: ["Race pace", "Phelps", "Descending rest"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Preparation", "Build speed and rehearse stroke mechanics", "Fast but technically stable", [
        createSetNode("warm-up", { label: "Progressive swim", reps: 1, distance: 300, interval: "6:00", notes: "Build each 100" }),
        createSetNode("drill", { label: "Drill / swim", reps: 4, distance: 50, interval: "1:00", notes: "25 drill + 25 swim" }),
        createSetNode("warm-up", { label: "Build 25s", reps: 4, distance: 25, interval: "0:40", intensity: 7 }),
      ]),
      section("Pace challenge", "Hold 100 race pace as rest disappears", "Identical target split; protect stroke length and breakout", [
        createSetNode("race-pace", { label: "Race-pace 50", reps: 4, distance: 50, interval: "1:30", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "1:20", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "1:10", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "1:00", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "0:50", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "0:40", targetTime: "0:28" }),
        createSetNode("race-pace", { label: "Race-pace 50", reps: 1, distance: 50, interval: "0:35", targetTime: "0:28" }),
      ]),
      section("Clearance", "Recover while maintaining mechanics", "Smooth and continuous", [createSetNode("recovery", { label: "Choice smooth", reps: 6, distance: 100, interval: "1:50" })]),
    ],
  },
  {
    id: "urbanchek-progressive-threshold",
    title: "Urbanchek-Inspired Progressive Threshold",
    subtitle: "A four-zone progression from comfortable aerobic swimming to above-threshold work.",
    attribution: "Inspired by Jon Urbanchek's color-zone training language",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Advanced",
    focus: "Progressive aerobic and threshold development",
    phase: "Aerobic base",
    durationMinutes: 90,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Threshold", "Urbanchek", "Energy zones"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare for four intensity zones", "Gradual effort increase", [
        createSetNode("warm-up", { label: "Choice swim", reps: 1, distance: 300, interval: "6:00" }),
        createSetNode("kick", { label: "Kick / swim descend", reps: 3, distance: 100, interval: "1:50", notes: "Descend 1-3" }),
        createSetNode("warm-up", { label: "Build 50s", reps: 3, distance: 50, interval: "1:00" }),
      ]),
      section("White zone", "Comfortable aerobic work", "10-20 seconds rest; relaxed control", [createSetNode("aerobic", { label: "White EN-1", reps: 4, distance: 200, interval: "3:10", intensity: 5 })]),
      section("Pink zone", "Working aerobic pace", "10-15 seconds rest; stable technique", [createSetNode("aerobic", { label: "Pink EN-1+", reps: 6, distance: 150, interval: "2:15", intensity: 6 })]),
      section("Red zone", "Threshold work", "Hold pace; no technical breakdown", [createSetNode("threshold", { label: "Red EN-2", reps: 8, distance: 100, interval: "1:25", intensity: 8 })]),
      section("Blue zone", "Above-threshold finish", "Fast but controlled; finish every wall", [createSetNode("threshold", { label: "Blue EN-2+", reps: 10, distance: 50, interval: "0:50", intensity: 9 })]),
      section("Cool-down", "Restore", "Long relaxed strokes", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "ledecky-threshold-inspired",
    title: "Ledecky-Inspired Threshold Builder",
    subtitle: "A descending-distance quality circuit mixing negative split work, strong repeats and sprint finishes.",
    attribution: "Modeled on publicly described Katie Ledecky threshold training",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Elite",
    focus: "Threshold capacity and speed reserve",
    phase: "Race preparation",
    durationMinutes: 95,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Threshold", "Ledecky", "Distance"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare aerobic system and speed", "Build progressively", [
        createSetNode("warm-up", { label: "Swim / kick / choice", reps: 1, distance: 600, interval: "12:00" }),
        createSetNode("warm-up", { label: "Build 50s", reps: 4, distance: 50, interval: "1:00" }),
        createSetNode("kick", { label: "Fast kick", reps: 4, distance: 25, interval: "0:40", intensity: 8 }),
      ]),
      section("Main set", "Move from long controlled work to maximum speed", "Negative split 300; stable strong 150s; exact 100s; full-quality 25s", [
        repeat("Threshold quality circuit", 3, [
          createSetNode("threshold", { label: "Negative-split 300", reps: 1, distance: 300, interval: "4:30", notes: "Second 150 faster" }),
          createSetNode("threshold", { label: "Strong 150s", reps: 3, distance: 150, interval: "2:10", intensity: 8 }),
          createSetNode("threshold", { label: "Fast 100s", reps: 3, distance: 100, interval: "1:35", intensity: 9 }),
          createSetNode("sprint", { label: "All-out 25s", reps: 6, distance: 25, interval: "0:40", intensity: 10 }),
          note("Round recovery", "Take 60 seconds between rounds."),
        ]),
      ]),
      section("Cool-down", "Flush and reset", "Easy", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "phelps-bowman-200-fly",
    title: "Phelps-Bowman 200 Fly Set - Adapted",
    subtitle: "Controlled butterfly 50s followed by faster 50s, repeated without extra rest between rounds.",
    attribution: "Based on a publicly reported Michael Phelps / Bob Bowman butterfly set",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/competitive-swimming-workouts/",
    level: "Elite",
    focus: "Butterfly endurance and speed control",
    phase: "Race preparation",
    durationMinutes: 75,
    poolLength: 25,
    poolUnit: "yd",
    tags: ["Butterfly", "Phelps", "Bowman"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare shoulders, rhythm and underwaters", "Low breathing tension; smooth body dolphin", [
        createSetNode("warm-up", { label: "Choice warm-up", reps: 1, distance: 800, interval: "16:00" }),
        createSetNode("drill", { label: "Butterfly drill", reps: 8, distance: 50, stroke: "Fly", interval: "1:00", notes: "25 drill + 25 swim" }),
      ]),
      section("Main butterfly set", "Alternate controlled endurance and high-speed 50s", "Control stroke count first; keep fast reps technically clean", [
        repeat("Fly endurance / speed round", 3, [
          createSetNode("threshold", { label: "Controlled butterfly", reps: 10, distance: 50, stroke: "Fly", interval: "0:45", targetTime: "0:29", intensity: 8, notes: "Stroke control" }),
          createSetNode("race-pace", { label: "Fast butterfly", reps: 5, distance: 50, stroke: "Fly", interval: "0:35", targetTime: "0:26", intensity: 10, notes: "No extra rest before next round" }),
        ]),
      ]),
      section("Recovery", "Protect shoulders after high fly volume", "Loose recovery and clean backstroke", [createSetNode("recovery", { label: "Easy back / free", reps: 1, distance: 600, stroke: "Choice", interval: "12:00" })]),
    ],
  },
  {
    id: "phelps-favorite-80x25",
    title: "Phelps' Favorite 80 x 25 - Adapted",
    subtitle: "Four-stroke drill and speed cycles built around short-course 25s.",
    attribution: "Based on a workout Bob Bowman identified as a Michael Phelps favorite",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/competitive-swimming-workouts/",
    level: "Advanced",
    focus: "Four-stroke skill and short speed",
    phase: "Speed phase",
    durationMinutes: 65,
    poolLength: 25,
    poolUnit: "yd",
    tags: ["IM", "Phelps", "Drill"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare all strokes", "Legal turns and controlled underwaters", [createSetNode("warm-up", { label: "IM choice warm-up", reps: 1, distance: 800, interval: "16:00", stroke: "IM Order" })]),
      section("80 x 25 skill-speed cycle", "Pair four drill repetitions with one fast swim for each stroke", "Drill with purpose; fast 25 keeps same technical cue", [
        repeat("Four-stroke cycle", 4, [
          createSetNode("drill", { label: "Fly drill", reps: 4, distance: 25, stroke: "Fly", interval: "0:35" }),
          createSetNode("sprint", { label: "Fly fast", reps: 1, distance: 25, stroke: "Fly", interval: "0:35" }),
          createSetNode("drill", { label: "Back drill", reps: 4, distance: 25, stroke: "Back", interval: "0:35" }),
          createSetNode("sprint", { label: "Back fast", reps: 1, distance: 25, stroke: "Back", interval: "0:35" }),
          createSetNode("drill", { label: "Breast drill", reps: 4, distance: 25, stroke: "Breast", interval: "0:35" }),
          createSetNode("sprint", { label: "Breast fast", reps: 1, distance: 25, stroke: "Breast", interval: "0:35" }),
          createSetNode("drill", { label: "Free drill", reps: 4, distance: 25, stroke: "Free", interval: "0:35" }),
          createSetNode("sprint", { label: "Free fast", reps: 1, distance: 25, stroke: "Free", interval: "0:35" }),
        ]),
      ]),
      section("Cool-down", "Easy reset", "Relaxed", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 400, interval: "8:00" })]),
    ],
  },
  {
    id: "marsh-high-end-speed",
    title: "David Marsh High-End Speed - Adapted",
    subtitle: "Progressively longer target-speed segments from push and dive starts, followed by easy swimming.",
    attribution: "Based on a publicly described David Marsh sprint workout",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/competitive-swimming-workouts/",
    level: "Elite",
    focus: "Top-end speed and lactate production",
    phase: "Speed phase",
    durationMinutes: 75,
    poolLength: 50,
    poolUnit: "m",
    tags: ["Sprint", "Marsh", "Starts"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare starts and maximum velocity", "Full shoulder range; progressive breakouts", [createSetNode("warm-up", { label: "Sprint preparation", reps: 1, distance: 1000, interval: "20:00", notes: "Swim, drill, kick, build and starts" })]),
      section("High-end speed", "Reach maximum speed, then extend it", "Time target-speed distance; easy to wall; alternate fins/no fins if appropriate", [
        repeat("Target-speed progression", 2, [
          createSetNode("sprint", { label: "15m target speed from push", reps: 1, distance: 75, interval: "3:00", notes: "15m race speed, easy remainder" }),
          createSetNode("sprint", { label: "20m target speed from push", reps: 1, distance: 75, interval: "3:00", notes: "20m race speed, easy remainder" }),
          createSetNode("sprint", { label: "20m target speed from dive", reps: 1, distance: 75, interval: "3:00", startMethod: "Dive" }),
          createSetNode("sprint", { label: "25m target speed from dive", reps: 2, distance: 75, interval: "3:00", startMethod: "Dive" }),
          createSetNode("sprint", { label: "35m target speed from dive", reps: 2, distance: 75, interval: "3:00", startMethod: "Dive" }),
          createSetNode("sprint", { label: "25m target speed from dive", reps: 1, distance: 75, interval: "3:00", startMethod: "Dive" }),
        ]),
        createSetNode("sprint", { label: "Dive target-speed 50 + easy 50", reps: 2, distance: 100, interval: "4:00", startMethod: "Dive", notes: "One quality rep, one fully easy rep" }),
      ]),
      section("Cool-down", "Clear lactate", "Long easy swimming", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 600, interval: "12:00" })]),
    ],
  },
  {
    id: "krayzelburg-backstroke-ladder",
    title: "Krayzelburg Backstroke Ladder - Adapted",
    subtitle: "Six rounds of 50-100-150 choice leading into a descending 200 backstroke.",
    attribution: "Based on Lenny Krayzelburg's publicly described 1999 backstroke set",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/competitive-swimming-workouts/",
    level: "Elite",
    focus: "200 backstroke endurance and descending speed",
    phase: "Race preparation",
    durationMinutes: 95,
    poolLength: 50,
    poolUnit: "m",
    tags: ["Backstroke", "Krayzelburg", "Ladder"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare backstroke line and turns", "Stable head; powerful underwaters", [createSetNode("warm-up", { label: "Backstroke preparation", reps: 1, distance: 1000, interval: "20:00", stroke: "Choice" })]),
      section("Main set", "Build volume before a descending 200 backstroke", "Choice work stays controlled; descend the 200 every round", [
        repeat("Backstroke ladder round", 6, [
          createSetNode("aerobic", { label: "Choice 50", reps: 1, distance: 50, interval: "0:50" }),
          createSetNode("aerobic", { label: "Choice 100", reps: 1, distance: 100, interval: "1:30" }),
          createSetNode("aerobic", { label: "Choice 150", reps: 1, distance: 150, interval: "2:10" }),
          createSetNode("race-pace", { label: "200 backstroke descend", reps: 1, distance: 200, stroke: "Back", interval: "2:40", intensity: 9, notes: "Descend time each round" }),
        ]),
      ]),
      section("Cool-down", "Shoulder recovery", "Long relaxed back/free", [createSetNode("recovery", { label: "Easy back / free", reps: 1, distance: 600, interval: "12:00" })]),
    ],
  },
  {
    id: "underwater-dolphin-practice",
    title: "Underwater Dolphin Kick Practice",
    subtitle: "A full skill session using back, side and resisted dolphin-kick positions.",
    attribution: "Inspired by the underwater dolphin kick practice collection",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Advanced",
    focus: "Underwater speed and technical range",
    phase: "General preparation",
    durationMinutes: 70,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Underwater", "Dolphin kick", "Fins"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Establish kick count on every wall", "Tight streamline; no dead spots", [createSetNode("warm-up", { label: "Choice swim and drill", reps: 1, distance: 500, interval: "10:00", notes: "Hold planned kick count" })]),
      section("Back-position power", "Build undulation and leg endurance", "Arms at side; movement starts through chest and hips", [createSetNode("underwater", { label: "Dolphin kick on back", reps: 6, distance: 100, interval: "2:30", equipment: ["Fins"], intensity: 8, notes: "60 sec quality recovery if needed" })]),
      section("Side-position timing", "Train both phases of the kick", "Alternate left/right by 25", [createSetNode("underwater", { label: "Side dolphin kick", reps: 12, distance: 50, interval: "1:20", equipment: ["Fins"], intensity: 8 })]),
      section("Resisted speed", "Remove dead spots and increase force", "Fast to 15m; stop if line breaks", [createSetNode("underwater", { label: "Resisted underwater sprint", reps: 16, distance: 15, interval: "0:45", equipment: ["Parachute"], intensity: 10 })]),
      section("Cool-down", "Reset", "Easy", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "kick-first-sprint-power",
    title: "Kick-First Sprint Power",
    subtitle: "A contrast session that loads the legs first, then transfers the kick into breakout and full-stroke speed.",
    attribution: "Adapted from SwimSwam's kick-first sprint training concept",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/training/swimming-workouts/",
    level: "Advanced",
    focus: "Kick power and sprint transfer",
    phase: "Power",
    durationMinutes: 70,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Kick", "Sprint", "Power"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare ankles, hips and breakouts", "Progress kick tempo without losing line", [createSetNode("warm-up", { label: "Choice warm-up", reps: 1, distance: 700, interval: "14:00", notes: "Include 8 breakout builds" })]),
      section("Kick-first contrast", "Create leg load before race-speed swimming", "Maximum kick frequency; preserve head and hip position", [repeat("Power contrast", 4, [createSetNode("kick", { label: "Fast kick", reps: 4, distance: 25, interval: "0:40", equipment: ["Fins"], intensity: 9 }), createSetNode("sprint", { label: "Breakout sprint", reps: 2, distance: 25, interval: "1:00", intensity: 10, notes: "Fast to 15m, easy to wall" }), createSetNode("recovery", { label: "Easy reset", reps: 1, distance: 100, interval: "2:15" })])]),
      section("Cool-down", "Restore length", "Relaxed kick", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "paddles-chute-power-hour",
    title: "Paddles and Chute Power Hour",
    subtitle: "Resisted pulling and short power swimming organized around quality rather than continuous fatigue.",
    attribution: "Adapted from SwimSwam's paddles-and-chute power workout concept",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/training/swimming-workouts/",
    level: "Advanced",
    focus: "Upper-body power and catch pressure",
    phase: "Power",
    durationMinutes: 60,
    poolLength: 25,
    poolUnit: "m",
    tags: ["Paddles", "Resistance", "Power"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare shoulders and catch", "Progress paddle size conservatively", [createSetNode("warm-up", { label: "Swim, scull and pull", reps: 1, distance: 800, interval: "16:00" })]),
      section("Resistance main set", "Apply force without shortening the stroke", "Stable core; pressure through the finish", [repeat("Power round", 5, [createSetNode("pull", { label: "Paddles pull strong", reps: 2, distance: 100, interval: "1:40", equipment: ["Paddles", "Pull buoy", "Snorkel"], intensity: 8 }), createSetNode("sprint", { label: "Chute power", reps: 4, distance: 25, interval: "0:50", equipment: ["Parachute"], intensity: 10 }), createSetNode("recovery", { label: "Easy swim", reps: 1, distance: 100, interval: "2:10" })])]),
      section("Cool-down", "Shoulder reset", "Long relaxed strokes", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 400, interval: "8:00" })]),
    ],
  },
  {
    id: "im-transition-challenge",
    title: "IM Transition Challenge",
    subtitle: "A medley practice that links legal turns, underwater speed and controlled pace changes between strokes.",
    attribution: "Adapted from competitive medley workout collections",
    sourceName: "SwimSwam",
    sourceUrl: "https://swimswam.com/competitive-swimming-workouts/",
    level: "Advanced",
    focus: "IM transitions and race rhythm",
    phase: "Race preparation",
    durationMinutes: 80,
    poolLength: 25,
    poolUnit: "m",
    tags: ["IM", "Turns", "Race pace"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare all strokes", "Legal finishes and clean breakouts", [createSetNode("warm-up", { label: "IM rotation warm-up", reps: 4, distance: 200, stroke: "IM Order", interval: "3:30" })]),
      section("Transition skills", "Repeat stroke changes with precision", "Attack into wall; hold streamline out", [createSetNode("drill", { label: "IM transition 50s", reps: 12, distance: 50, stroke: "IM Order", interval: "1:15", notes: "25 into transition + 25 out" })]),
      section("Main set", "Hold event rhythm under changing strokes", "No weak transition; controlled first half", [repeat("IM race round", 4, [createSetNode("race-pace", { label: "100 IM race rhythm", reps: 2, distance: 100, stroke: "IM", interval: "2:00", intensity: 9 }), createSetNode("threshold", { label: "200 IM smooth-fast", reps: 1, distance: 200, stroke: "IM", interval: "3:30", intensity: 8 }), createSetNode("recovery", { label: "Easy free/back", reps: 1, distance: 100, interval: "2:00" })])]),
      section("Cool-down", "Reset shoulders and hips", "Easy choice", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  },
  {
    id: "busy-swimmer-30-minute",
    title: "Thirty-Minute Quality Session",
    subtitle: "A compact practice for limited pool time with technique, aerobic work and short race-speed efforts.",
    attribution: "Inspired by YourSwimLog's shorter workout collections",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/swimming-workouts/",
    level: "Intermediate",
    focus: "Efficient mixed-quality training",
    phase: "General preparation",
    durationMinutes: 30,
    poolLength: 25,
    poolUnit: "m",
    tags: ["30 minute", "Technique", "Mixed"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Get moving quickly", "Smooth walls and breathing", [createSetNode("warm-up", { label: "Progressive choice", reps: 1, distance: 400, interval: "7:00" })]),
      section("Quality mix", "Touch several systems without excessive volume", "Technique stays clean as speed rises", [repeat("Compact round", 3, [createSetNode("drill", { label: "Drill to swim", reps: 2, distance: 50, interval: "1:00" }), createSetNode("aerobic", { label: "Strong aerobic", reps: 2, distance: 100, interval: "1:35", intensity: 7 }), createSetNode("sprint", { label: "Fast 25", reps: 4, distance: 25, interval: "0:35", intensity: 9 })])]),
      section("Cool-down", "Lower heart rate", "Relaxed", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 200, interval: "4:00" })]),
    ],
  },
  {
    id: "broken-200-pace-builder",
    title: "Broken 200 Pace Builder",
    subtitle: "Progresses from controlled 50s to a broken event-distance rehearsal with recorded cumulative time.",
    attribution: "Inspired by race-pace workout articles from YourSwimLog",
    sourceName: "YourSwimLog",
    sourceUrl: "https://www.yourswimlog.com/articles/",
    level: "Advanced",
    focus: "200-event pacing and closing speed",
    phase: "Race preparation",
    durationMinutes: 75,
    poolLength: 25,
    poolUnit: "m",
    tags: ["200 pace", "Broken swim", "Splits"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare event stroke and turns", "Build final 200", [createSetNode("warm-up", { label: "Event-stroke warm-up", reps: 1, distance: 900, interval: "18:00" })]),
      section("Pace preparation", "Find target 50 pace", "Record every split", [createSetNode("race-pace", { label: "Target 50s", reps: 8, distance: 50, interval: "1:15", targetTime: "", intensity: 8 })]),
      section("Broken 200", "Rehearse race shape with controlled recovery", "First 100 controlled; close aggressively", [repeat("Broken 200 round", 3, [createSetNode("race-pace", { label: "50 at first-100 pace", reps: 2, distance: 50, intervalMode: "rest", restSeconds: 10, interval: "0:45", intensity: 9 }), createSetNode("race-pace", { label: "50 at third-50 pace", reps: 1, distance: 50, intervalMode: "rest", restSeconds: 15, interval: "0:50", intensity: 9 }), createSetNode("sprint", { label: "50 closing speed", reps: 1, distance: 50, interval: "1:30", intensity: 10 }), createSetNode("recovery", { label: "Easy between rounds", reps: 1, distance: 200, interval: "4:00" })])]),
      section("Cool-down", "Clear fatigue", "Easy", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 400, interval: "8:00" })]),
    ],
  },
  {
    id: "masters-pace-rotation",
    title: "Masters Pace Rotation",
    subtitle: "A scalable pace workout with short race-pace repetitions, aerobic recovery and coach-controlled miss rules.",
    attribution: "Adapted from US Masters Swimming pace-workout guidance",
    sourceName: "US Masters Swimming",
    sourceUrl: "https://www.usms.org/fitness-and-training/articles-and-videos/articles/best-workouts-for-masters-swimmers",
    level: "Intermediate",
    focus: "Repeatable race pace for mixed-ability adults",
    phase: "Race preparation",
    durationMinutes: 60,
    poolLength: 25,
    poolUnit: "yd",
    tags: ["Masters", "Race pace", "USRPT"],
    disclaimer: sourceDisclaimer,
    nodes: [
      section("Warm-up", "Prepare safely and establish pace", "Gradual intensity", [createSetNode("warm-up", { label: "Choice warm-up", reps: 1, distance: 700, interval: "14:00" })]),
      section("Pace rotation", "Repeat race-specific speed with enough easy work to preserve quality", "Stop or adjust when pace repeatedly drops", [repeat("Pace rotation", 3, [createSetNode("USRPT", { label: "Race-pace 25s", reps: 8, distance: 25, interval: "0:30", missLimit: 3, intensity: 9 }), createSetNode("recovery", { label: "Easy aerobic", reps: 1, distance: 200, interval: "3:30" }), createSetNode("race-pace", { label: "Race-pace 50s", reps: 4, distance: 50, interval: "1:00", intensity: 9 }), createSetNode("recovery", { label: "Easy reset", reps: 1, distance: 100, interval: "2:00" })])]),
      section("Cool-down", "Finish relaxed", "Long strokes", [createSetNode("recovery", { label: "Easy choice", reps: 1, distance: 300, interval: "6:00" })]),
    ],
  }
];

export const FAMOUS_WORKOUT_TAGS = [...new Set(FAMOUS_WORKOUTS.flatMap((workout) => workout.tags))].sort();
